#!/bin/bash

cat bashrc >> ~/.bash_aliases

if cat /bin/update; then
    echo "auto-cat: /bin/update already exists! Not replacing it."
else
    cp update.sh ~/update.sh
    mv ~/update.sh ~/update
    sudo mv ~/update /bin/update
    echo "update script moved to /bin/update. Printing results of"
    echo "\$ cat /bin/update ..."
    cat /bin/update
fi

./run_me_once.sh